"""Very basic offline chatbot for GrihaNet."""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required

chat_bp = Blueprint("chat", __name__)

RULES = {
    ("power", "electricity", "energy", "watt", "kwh", "cost", "budget"): 
        "The Power tab tracks your live electricity usage in kilowatts (kW) and tallies your daily/monthly costs. You can turn individual appliances on/off from there to save energy. If you exceed your set budget, you'll receive a warning alert!",
    
    ("camera", "security", "motion", "cctv", "video"): 
        "The Cameras tab shows simulated live feeds from your smart home. Our backend motion-engine randomly simulates events (like detecting a Person, Delivery, or Vehicle) and logs them in real-time.",
    
    ("automation", "rule", "ifttt", "trigger", "action", "smart"): 
        "The Automations tab is the brain of GrihaNet! You can create 'If This Then That' rules. For example: 'If power exceeds 5kW, turn off the Geyser' or 'If a Person is detected, turn on the porch lights'. The background engine checks rules every 10 seconds.",
    
    ("network", "bandwidth", "device", "mac", "ip", "block", "internet"): 
        "The Network tab lists every device connected to your home Wi-Fi. You can see their bandwidth usage and immediately 'Block' unknown devices to restrict their internet access.",
    
    ("admin", "member", "role", "user", "password"): 
        "Since you are an Admin, you have access to the 🛡️ Admin tab. From there, you can view all users, promote them to admin, reset their passwords, suspend their accounts, or add new members directly.",
    
    ("alert", "notification", "warn"): 
        "The Alerts tab captures important events generated by your Automations or system thresholds (like high power usage). You can clear them once you've read them.",
    
    ("hello", "hi", "hey"): 
        "Hello! 👋 I'm your friendly GrihaNet assistant. How can I help you manage your smart home today?",
}

FALLBACK_RESPONSE = (
    "I am a very basic offline assistant. I don't use AI models to save on resources! "
    "Try asking me about specific features like **power**, **cameras**, **automations**, or your **network**."
)

@chat_bp.route("/ask", methods=["POST"])
@jwt_required()
def ask():
    data = request.get_json() or {}
    message = data.get("message", "").lower()

    if not message:
        return jsonify({"reply": "Please send a message."}), 400

    reply = FALLBACK_RESPONSE
    
    # Simple keyword matching
    for keywords, response in RULES.items():
        if any(kw in message for kw in keywords):
            reply = response
            break

    return jsonify({"reply": reply})
